---
name: fail2ban
version: dev-1
slug: fail2ban
description: Manage Nginx proxy hosts with a simple, powerful interface
url: https://github.com/hassio-addons/addon-nginx-proxy-manager
codenotary: codenotary@frenck.dev
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
host_network: true
map:
  - config:rw
  - share:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
