---
name: fail2ban
version: 0.9
slug: fail2ban
description: Fail2ban is an intrusion prevention software framework.
url: https://github.com/d-two/hassio-addons-edge/fail2ban
codenotary: the.dtwo@gmail.com
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
host_network: true
privileged:
  - NET_ADMIN
  - NET_RAW
map:
  - config:rw
  - share:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
