---
name: MediaElch
slug: mediaelch
version: latest
description: MediaElch is a MediaManager for Kodi. Information about Movies, TV Shows, Concerts and Music are stored as NFO files. Fanarts are downloaded automatically from fanart.tv.
url: https://github.com/d-two/hassio-addons
startup: application
init: false
panel_icon: mdi:multimedia
ingress: true
ingress_port: 5800
webui: "http://[HOST]:[PORT:5800]"
arch:
- aarch64
- amd64
- armhf
- i386
boot: auto
map:
- media:rw
#ports:
#  5800/tcp: 5800
#ports_description:
#  5800/tcp: Web UI port
