---
name: Honeypot
version: beta-2
slug: honeypot
description: SSH Honeypot
url: https://github.com/hassio-addons/honeypot
codenotary: the.dtwo@gmail.com
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
ports:
  22/tcp: 22
ports_description:
  22/tcp: SSH Port
map:
  - share:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
