---
build_from:
  armhf: ghcr.io/hassio-addons/debian-base:6.2.6
  armv7: ghcr.io/hassio-addons/debian-base:6.2.6
  aarch64: ghcr.io/hassio-addons/debian-base:6.2.6
  amd64: ghcr.io/hassio-addons/debian-base:6.2.6
  i386: ghcr.io/hassio-addons/debian-base:6.2.6
