---
name: TVHeadend
version: dev
stage: experimental
slug: tvheadend_dev
description: TV streaming server and recorder.
url: "https://github.com/GauthamVarmaK/addon-tvheadend"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
webui: "http://[HOST]:[PORT:9981]/"
hassio_role: admin
hassio_api: true
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
devices:
  - /dev/dvb
  - /dev/dri
ports:
  9981/tcp: 9981
  9982/tcp: 9982
ports_description:
  9981/tcp: TVH Web Interface
  9982/tcp: TVH HTSP
map:
  - "config:rw"
  - "media:rw"
options:
  system_packages: []
  init_commands: []
  webgrabplus: false
  picons: false
  snp_url: ""
  srp_url: ""
schema:
  system_packages:
    - str
  init_commands:
    - str
  webgrabplus: bool
  picons: bool
  snp_url: str
  srp_url: str
