---
name: GeoIP-Grafana
version: dev-1
slug: geoip_grafana
description: GeoIP-Grafana
url: https://github.com/hassio-addons/honeypot
codenotary: the.dtwo@gmail.com
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
map:
  - share:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  influx_user: str
  influx_pw: str
  influx_db: str
  influx_host: str
  influx_port: int
